export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const API = "API";
export const FETCH_USER = "FETCH_USER";
export const LOGOUT = "LOGOUT";

export const SPOTIFY_REQUEST = "SPOTIFY_REQUEST";

export const REQUEST_ARTIST = "REQUEST_ARTIST";
export const FETCH_ARTIST = "FETCH_ARTIST";
export const SELECTED_ARTIST = "SELECTED_ARTIST";
export const ARTIST_SUCCESS = "ARTIST_SUCCESS";

export const FETCH_FAILED = "FETCH_FAILED";

export const FETCH_SONG = "FETCH_SONG";
export const REQUEST_SONG = "REQUEST_SONG";
export const SONG_SUCCESS = "SONG_SUCCESS";

export const REQUEST_PLAYLIST = "REQUEST_PLAYLIST";
export const FETCH_PLAYLIST = "FETCH_PLAYLIST";
export const SELECTED_PLAYLIST = "SELECTED_PLAYLIST";
export const PLAYLIST_SUCCESS = "PLAYLIST_SUCCESS";

export const REQUEST_GENRE = "REQUEST_GENRE";
export const FETCH_GENRE = "FETCH_GENRE";
export const SELECTED_GENRE = "SELECTED_GENRE";
export const GENRE_SUCCESS = "GENRE_SUCCESS";

export const CLEAR_SEARCH = "CLEAR_SEARCH";

export const FETCH_YOUTUBE = "FETCH_YOUTUBE";
export const YOUTUBE_SUCCESS = "YOUTUBE_SUCCESS";
export const REQUEST_YOUTUBE = "REQUEST_YOUTUBE";

export const PLAY_SONG = "PLAY_SONG";
export const PLAY_SPOTIFY = "PLAY_SPOTIFY";
export const PAUSE_SPOTIFY = "PAUSE_SPOTIFY";
